export TF_VAR_access_key=AKIAJIIA46RTGJTMWY6Q
export TF_VAR_secret_key=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
export TF_VAR_ami=ami-c737a5a7
export TF_VAR_region=us-west-2
export TF_VAR_key_name=testdb3_key
export TF_VAR_instance_type=t1.micro
export TF_VAR_name=testdb3_Us-West
