export TF_VAR_tenancy_ocid=ocid1.tenancy.oc1..aaaaaaaa7qrtmx66usnq3ijgsx5wem4jtncur2nioncm6v3xo7qciujtgwhq
export TF_VAR_subnet_id=ocid1.subnet.oc1.phx.aaaaaaaal5d6p4phh3fp44i5zogicl4ghhrmyvntgiwrh2b2dusu7ie2ys6a
export TF_VAR_user_ocid=ocid1.user.oc1..aaaaaaaazzblnyjmimg4oepnfvx4hfyuuajvrrfi7ewdzzugf5tah33cw73a
export TF_VAR_fingerprint=1c:5a:f5:a6:71:a5:f7:b6:00:c3:b1:fc:ec:ca:a4:f5
export TF_VAR_private_key_path=/opt/orchestration/bmcs/oraclebmc/bmcs_api_key.pem
export TF_VAR_ssh_authorized_keys=/opt/orchestration/bmcs/oraclebmc/ssh_authorized_keys.pub
export TF_VAR_private_key_password=pass
export TF_VAR_ssh_authorized_private_keys=/opt/orchestration/bmcs/oraclebmc/ssh_authorized_keys.pem
export TF_VAR_compartment_ocid=ocid1.compartment.oc1..aaaaaaaa6qol5npt7axqzq4ijrcds2mv7dxyj7wmnojl4jrmlmipr2nq7w6a
export TF_VAR_vm_image_ocid=ocid1.image.oc1.phx.aaaaaaaazt3sfrz2lfbha6okihvh4bwaufikhilhsek43hpvzxitl47nv2bq
export TF_VAR_shape=VM.Standard1.2
export TF_VAR_label=Testdb1
export TF_VAR_availability_domain=Rmpq:PHX-AD-1

